name: Deploy News Bot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          if [ -f test-downloaders.js ]; then
            npm test || echo "No tests found or tests failed."
          else
            echo "No test file found. Skipping tests."
          fi

      # Add your deployment step here. For Railway, use the Railway CLI.
      - name: Install Railway CLI
        run: npm install -g railway

      - name: Deploy to Railway
        if: github.ref == 'refs/heads/main'
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      # If deploying elsewhere, replace the above step with your platform's deploy action or script. 
